import vintage1 from "./vintage_1.png";
import vintage2 from "./vintage_2.png";
import shirt2 from "./shirt_2.png";
import shirt1 from "./shirt_1.png";

export const ProductData = [
  {
    id: 1,
    slug: "vintage1",
    category: "Shirt",
    imageUrl: vintage1,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: true,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$33.00",
  },
  {
    id: 2,
    slug: "shirt2",
    category: "Shirt",
    imageUrl: shirt2,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: false,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$12.00",
  },
  {
    id: 3,
    slug: "shirt3",
    category: "Shirt",
    imageUrl: shirt2,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: false,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$18.00",
  },
  {
    id: 4,
    slug: "shirt4",
    category: "Shirt",
    imageUrl: shirt1,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: true,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$42.00",
  },
  {
    id: 5,
    slug: "vintage5",
    category: "Shirt",
    imageUrl: vintage2,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: false,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$18.00",
  },
  {
    id: 6,
    slug: "vintage6",
    category: "Shirt",
    imageUrl: vintage2,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: true,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$12.00",
  },
  {
    id: 7,
    slug: "vintage7",
    category: "Shirt",
    imageUrl: vintage1,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: false,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$10.00",
  },
  {
    id: 8,
    slug: "shirt8",
    category: "Shirt",
    imageUrl: shirt1,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: true,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$13.00",
  },
  {
    id: 9,
    slug: "shirt9",
    category: "Shirt",
    imageUrl: shirt2,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: true,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$12.00",
  },
  {
    id: 10,
    slug: "vintage10",
    category: "Shirt",
    imageUrl: vintage1,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: false,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$12.00",
  },
  {
    id: 11,
    slug: "vintage11",
    category: "Shirt",
    imageUrl: vintage2,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: false,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$9.00",
  },
  {
    id: 12,
    slug: "shirt12",
    category: "Shirt",
    imageUrl: shirt1,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: false,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$12.00",
  },
  {
    id: 13,
    slug: "shirt13",
    category: "Shirt",
    imageUrl: shirt2,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: true,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$11.99",
  },
  {
    id: 14,
    slug: "shirt14",
    category: "Shirt",
    imageUrl: shirt2,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: false,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$24.00",
  },
  {
    id: 15,
    slug: "vintage15",
    category: "Shirt",
    imageUrl: vintage1,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: true,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$12.00",
  },
  {
    id: 16,
    slug: "shirt16",
    category: "Shirt",
    imageUrl: shirt1,
    description: "Essentials Men's Short-Sleeve Crewneck T-Shirt",
    isFavorite: false,
    isRated: true,
    totalRating: 23456,
    rating: 4.9,
    price: "$14.00",
  },
];

export const NavItems = [
  {
    id: "home",
    icon: "",
    name: "Home",
    path: "/",
  },
  {
    id: "ticket",
    icon: "",
    name: "Voucer",
    path: "/voucher",
  },
  {
    id: "wallet",
    icon: "",
    name: "Wallet",
    path: "/wallet",
  },
  {
    id: "settings",
    icon: "",
    name: "Settings",
    path: "/settings",
  },
];
